export enum CertificateStatus {
  CERTIFICATE_BLOCKED = 'CERTIFICATE_BLOCKED', // 0
  CERTIFICATE_VALID = 'CERTIFICATE_VALID', // 1
  CERTIFICATE_REVOKED = 'CERTIFICATE_REVOKED', // 2
  CERTIFICATE_EXPIRED = 'CERTIFICATE_EXPIRED', // 3
}
