export enum CertificationPermission {
  NO_CHANGE_PERMITTED = 'NO_CHANGE_PERMITTED', // 0
  MINIMAL_CHANGES_PERMITTED = 'MINIMAL_CHANGES_PERMITTED', // 1
  CHANGES_PERMITTED = 'CHANGES_PERMITTED', // 2
}
