export enum DeadlineType {
  DEADLINE_TYPE_FLEXIBLE_MANDATORY = 'DEADLINE_TYPE_FLEXIBLE_MANDATORY', // 0
  DEADLINE_TYPE_STRONG_MANDATORY = 'DEADLINE_TYPE_STRONG_MANDATORY', // 1
  DEADLINE_TYPE_FLEXIBLE_OPTIONAL = 'DEADLINE_TYPE_FLEXIBLE_OPTIONAL', // 2
  DEADLINE_TYPE_STRONG_OPTIONAL = 'DEADLINE_TYPE_STRONG_OPTIONAL', // 3
}
